### ISSUE TITLE
Seems to conflict with another (or other) mods.

### ISSUE THREAD

**Issue by abordoli** [FKuerten/factorio-chunk-sized-roboports#1]
I will keep troubleshooting and try to figure out which one, but my guess is wormmus config. If you know, please let me know and I'll close the issue.
Regards,
~B

**Comment by abordoli** [comment]
I de-toggled Worrmus and got the same error. Might as well see if you can figure it out:

Error loading mods

Failed to load mods: _ _chunk sized roboports_ _/data updates:lua:1: _ _chunk sized roboports_ _/prototypes/util.lua:7:bad argument #1 to 'ipairs' (table expected, got nil)

Mods to be disabled:
* chunk sized robotports

Now, I did have this working in an earlier save and the one that I'm trying it in is a new world  so that I can implement the new sub-station/pole/roboports in the next.

If you've got no clue from the error, then I'll have to keep digging deeper as to what new mods I added that might be adversely affecting your mod.
~B

**Comment by abordoli** [comment]
Not sure what it means by "abordoli closed this ....". I didn't think I may have hit a buttom assuming it was saving the comment.

**Comment by abordoli** [comment]
Seems fixed now...

**Comment by abordoli** [comment]
The open state, that is, is fixed. i'm still having issue with the mod not wanting to pass the "boot-up" sequence.

**Comment by abordoli** [comment]
I have found the conflicting mod. AAI Industries (in whole or in part). Are you on Discord so that we can discuss?
 ~B

**Comment by abordoli** [comment]
I m implementing a version of your mod without all the code at the very bottom that attempts to "bandage" things, but as a byproduct creates "Lake Worlds" even when you set water only in the Starting Area. I will keep you posted. Are you on Discord?

**Comment by abordoli** [comment]
I ran the test and it isn't your mod producing the "Lake World"....It is Alien Biomes producing it. The author is a friend and we're going to work through it. Thanks for your help!

**Comment by FKuerten** [comment]
I am sorry that I could not answer earlier.
Apparently my mod tries to "bandage" a recipe without "ingredients". I obviously have overlooked this case, but to be honest that is a corner case. It probably is a recipe that takes no ingredients.
Adding the following before line 7 (such that it becomes line 7) should fix this. I will probably update this later.
    `if not ingredients then return end`

I would also be interested in your fix. Also a complete stack trace, maybe allowing me to see which recipe exactly this was, would be useful.
I will reopen this until I added this change.

**Comment by abordoli** [comment]
Brilliant! I will add this code immediately and test it.

**Comment by abordoli** [comment]
I also may have cross communicated different issues (now that I read back) between a several mods that aren't working in unison (or giving the desired results)
-AAI Industries
-Chunk Size Roboports (direct conflict with the above)

and

-Alien Biomes
-Snow-Rock-Planet (selects individual biomes of the above)
-no lakes (attempt to fix the "Lake Worlds" being produced by the above two

I know this seems like extra information, but I include it in case you may have gotten confused by a reference to one of these.

P.S. Wormmus did fix his mod to work well with yours so the initial problem IS resolved.

**Comment by abordoli** [comment]
How do you run a stack trace in Factorio? Is it in the debug menu and dumps to a log?

**Comment by abordoli** [comment]
So far (by adding that line of code), this mod is now agreeable with AAI Industries, so that's a start.

**Comment by abordoli** [comment]
Oh, the recipes could have been any number of new recipes that AAI industries adds, like motor parts. Is that what you mean?

**Comment by FKuerten** [comment]
To answer you question: In your factorio folder (for me its %APPDATA%/Factorio) there should be log files.
Right after a crash the current log file will contain the stacktrace.

Also I finally added the change mentioned above. The mod should be more robust now.

**Comment by abordoli** [comment]
I believe everything is working fine, atm.
